### ISSUE TITLE
BukyVede font

### ISSUE THREAD

**Issue by nikolay** [caskroom/homebrew-fonts#568] opened 2016-05-06 03:35 UTC
http://kodeks.uni-bamberg.de/aksl/Schrift/BukyVede.htm

**Comment by guerrero** [comment] 2016-08-28 02:13
I can contribute to create a Cask for this font but the problem is that the download file comes without compression. I don't know what I should do in this type of cases and I haven't find a Cask to use as a reference.

@vitorgalvao do you know if it's possible to create a cask from an uncompressed file? Is there any Cask example to use as a reference?

**Comment by vitorgalvao** [comment] 2016-09-02 15:22
> @vitorgalvao do you know if it's possible to create a cask from an uncompressed file?

You’re looking for [`container :naked`](https://github.com/caskroom/homebrew-cask/blob/e1f08a1d5a7bf12ea9d4edd6cef6cbe1d49ab1b8/Casks/parse.rb#L13). But are you sure you need it? Font casks usually do fine without it ([example](https://github.com/caskroom/homebrew-fonts/blob/74ed7ee16bce602b261a580a454a2b8d0ec49160/Casks/font-zeyada.rb)).

**Comment by reitermarkus** [comment] 2016-09-11 21:53
I think the problem here is that every weight is a separate download.

**Comment by vitorgalvao** [comment] 2016-10-16 19:46
Closing for lack of interest.

**Closed by vitorgalvao** 2016-10-16 19:46 UTC
Labels: font request

**Comment by guerrero** [comment] 2016-11-01 17:05
Sorry for the late response, I am so sorry about it. I've created three different casks, one for each font weight, following your contributing docs. The download link for the light weight returns an error and I haven't been able to fix it or found the correct link.

Thanks for the support and sorry again!

**Comment by nikolay** [comment] 2016-11-01 20:57
Thank you very much, @guerrero! Just in time! Today is a very big national holiday in Bulgaria, which celebrates our nation's literacy, and adding this special font on this special day is very symbolic! Thank you very much form all Bulgarians!

**Comment by guerrero** [comment] 2016-11-02 11:36
Hey @nikolay! Glad to know that, I was in Sofia one month ago and I meet a lot of wonderful people there, so Bulgarians deserve it and much more :). Thank you for making my day!
